# https://docs.docker.com/reference/cli/docker/compose/
# https://docs.docker.com/compose/compose-file/05-services/

name: app_spacex
services:
  db:
    container_name: sagirov_postgres
    image: postgres:15
    #   working_dir: /sagirov/postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    #      - ./data/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER: postgres
#      - POSTGRES_DB: spacex
#      - POSTGRES_PASSWORD: 123
      # - ~/.pg/pg_data/sagirov:/var/lib/postgresql/data
    env_file: ./.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "${POSTGRES_USER} -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5 # That is  five restarts
    ports:
      - 8080:8080
  web:
    container_name: sagirov_django
    # image: first_image:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /frontend
    volumes:
      - db_data: /frontend/backup/data
      - .: /frontend
    env_file: ./.env
    command:
      - bash
      - -c
      - |         
        python3 ./manage.py collectstatic --noinput
        python3 manage.py makemigrations
        python3 manage.py migrate
        gunicorn -c 0.0.0.0:8000 project.wsgi:application
    ports:
      - 8000:8000
    depends_on:
      - db
  nginx:
    container_name: sagirov_nginx
    working_dir: /backend
    build:
      context: ./docker/nginx
      dockerfile: nginx.Dockerfile
    depends_on:
      - web
    volumes:
      - .:/docker/nginx
    restart: on-failure
      # guincorn sagirov.project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - '${NGINX_EXTERNAL_PORT}:80'

volumes:
  db_data:
    external: true

