# Generated by Django 5.0.6 on 2024-07-04 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок меню уникальный и не более 20 символов', max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces', regex='^[a-zA-Z\\s]+$')])),
                ('pathname', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='URL path must start and end with a forward slash and contain only letters, numbers, underscores and hyphens', regex='^[a-zA-Z0-9_-]+/?$'), django.core.validators.MaxLengthValidator(limit_value='Страница сайта', message='Check this position'), django.core.validators.MinLengthValidator(limit_value=2, message='Check this position')])),
            ],
        ),
        migrations.CreateModel(
            name='MenuModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mewnu_item', models.ManyToManyField(related_name='menus', to='spacex.menuitemmodels')),
            ],
        ),
    ]
