# Generated by Django 5.0.6 on 2024-07-04 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmodels',
            name='pathname',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='URL path must start and end with a forward slash and contain only letters, numbers, underscores and hyphens', regex='^[a-zA-Z0-9_-]+/?$'), django.core.validators.MaxLengthValidator(limit_value='Страница сайта', message='Check this position'), django.core.validators.MinLengthValidator(limit_value='2', message='Check this position')]),
        ),
    ]
