# Generated by Django 5.0.6 on 2024-07-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0003_alter_menuitemmodels_pathname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmodels',
            name='pathname',
            field=models.CharField(max_length=200),
        ),
    ]
