# Generated by Django 5.0.6 on 2024-07-04 06:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0004_alter_menuitemmodels_pathname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmodels',
            name='pathname',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='URL path must start and end with a forward slash and contain only letters, numbers, underscores and hyphens', regex='^[a-zA-Z0-9_-]+/?$')]),
        ),
        migrations.AlterField(
            model_name='menuitemmodels',
            name='title',
            field=models.CharField(help_text='Заголовок меню уникальный и не более 20 символов', max_length=20),
        ),
    ]
