# Generated by Django 5.0.6 on 2024-07-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0006_alter_menuitemmodels_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuModels',
        ),
    ]
