# Generated by Django 5.0.6 on 2024-07-04 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0009_alter_menuitemmodels_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmodels',
            name='title',
            field=models.CharField(help_text='Заголовок меню уникальный и не более 20 символов', max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces', regex='^[\\u0400-\\u04FF\\w\\s_-]+$')]),
        ),
    ]
