# Generated by Django 5.0.6 on 2024-07-04 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0010_alter_menuitemmodels_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(help_text='Первая строка не более 20 символов', max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters', regex='^[\\u0400-\\u04FF- _a-zA-Z]{1,20}$')])),
                ('number', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='URL path must start and end with a forward slash and contain only letters, numbers, underscores and hyphens', regex='^\\/?[0-9%]{1,4}/?$')])),
                ('second', models.CharField(help_text='Последняя строка и не более 20', max_length=20, validators=[django.core.validators.RegexValidator(message='Line must contain only letters', regex='^[\\u0400-\\u04FF- _a-zA-Z]{1,20}$')])),
            ],
        ),
        migrations.AlterField(
            model_name='menuitemmodels',
            name='title',
            field=models.CharField(help_text='Заголовок меню не более 20 символов', max_length=20, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces', regex='^[\\u0400-\\u04FF\\w\\s_-]+$')]),
        ),
    ]
